### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by Twizwei** [facebookresearch/instpred#3]
Hi there,

I'm trying to train the F2F5 right now but it seems it's pretty slow. I'm using 6 Titan X to train but after 2 hours the program is still stuck on Training epoch 1. Could you please provide an approximate time for training F2F5? Thanks!  

`INFO - 06/27/19 14:59:23 - 0:00:49 - -------------------------- Training epoch #1 --------------------------
[I net_async_base.h:206] Using specified CPU pool size: 32; device id: -1
[I net_async_base.h:211] Created new CPU pool, size: 32; device id: -1
`

**Comment by paulineluc** [comment]
Hi Yiran,

Training the network for 80 epochs took a little under 10 hours using a
single GPU.

The message looks like it's saying that you're training with CPU ? Perhaps
this thread can be of help ?
https://github.com/facebookresearch/DensePose/issues/43
